max_rng: 8.0                              # lidar max range [m]

th_r: 80                                  # lidar data processing range [deg]

std_dev_thr: 0.045                         # standard deviation threshold [m]

p_gain: 25                                # control p gain

vel: 0.07                                 # default velocity [m/s]
